remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Yijie Yang
logo: /assets/logo.jpg
description: "Actively looking for a job"
email: hinorth16@gmail.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/wowNorth0516/
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/yijieyang-north
    
navigation:
  - name: Aboutme
    link: https://wownorth0516.github.io/yijie.portfolio/myresume/
  - name: Project
    link: https://wownorth0516.github.io/yijie.portfolio/project/


# theme: jekyll-theme-minimal

